apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pods
  name: pods
spec:
  containers:
  - args:
    - p2
    image: nginx
    name: pods
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 300Mi
        cpu: 300m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
