apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quota-test
  name: quota-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quota-test
  template:
    metadata:
      labels:
        app: quota-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 300m
